### ISSUE TITLE
Please add a license

### ISSUE THREAD

**Issue by ravidsrk** [vgrec/SectionedActionBarList#1]
This repo is missing a license. Without a license, all code is copyright the author and may not be used by anyone else.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by vgrec** [comment]
Hi Ravindra,

Thanks for pointing out the missing license.
The library was updated with the Apache License V2.

On Fri, Feb 19, 2016 at 7:56 AM, Ravindra Kumar notifications@github.com
wrote:

> This repo is missing a license. Without a license, all code is copyright
> the author and may not be used by anyone else.
> 
> Please use something like http://choosealicense.com/ to decide what
> license to use. I recommend MIT or GPL.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/vgrec/SectionedActionBarList/issues/1.

## 

_------------------------------------------------------------------_
http://androidresearch.wordpress.com - Personal Blog
A few Android apps
https://play.google.com/store/apps/developer?id=Veaceslav+GREC done in my
spare time.
http://practichtml.go.ro - Curs de HTML pentru incepatori

Thank you,
Veaceslav GREC.

**Comment by ravidsrk** [comment]
Thanks
